import cipherTools
import pyglet

print("a")

for shift in cipherTools.caesar('''"HKWHHSF WG O KCBRSFTIZ HVWBU TCF AS, PSQOIGS W USH HVS KCFR CIH… W AWUVH BCH PS VSFS HOZYWBU HC MCI FWUVH BCK OG DFSGWRSBH WT W RWRB\'H VOJS OB VCBSGH KOM CT USHHWBU HVS KCFR CIH," VS GOWR.\nOTHSF HKWHHSF\'G BSK CKBSF SZCB AIGY FSJSFGSR AF HFIAD\'G DSFAOBSBH GIGDSBGWCB, MCI AWUVH VOJS HVCIUVH HVS TCFASF DFSGWRSBH KCIZR XIAD OH HVS QVOBQS HC QCAS POQY. PIH GC TOF, VS VOGB\'H HOYSB ID HVOH CTTSF.\nKVM?\nKSZZ, CBZM RCBOZR HFIAD YBCKG HVS OBGKSF HC HVOH EISGHWCB TCF GIFS.\nPIH KVOH KS RC YBCK WG VS VOG O ZCH CT ACBSM HC ZCGS TFCA HKSSHWBU.\n"HVS GWADZSGH SLDZOBOHWCB WG HVS ACGH ZWYSZM - WH'G OPCIH ACBSM," GOMG XCGV HIQYSF, DFCTSGGCF CT DCZWHWQG OH BSK MCFY IBWJSFGWHM (BMI).\nOTHSF RCBOZR HFIAD KOG YWQYSR CTT HKWHHSF, VS QFSOHSR VWG CKB GCQWOZ ASRWO DZOHTCFA QOZZSR HFIHV GCQWOZ - HVOH ZCCYG OB OKTIZ ZCH ZWYS HKWHHSF.
'''):
    print("ewdsnja")
    score = cipherTools.char_frequency(shift)
    print(f"{score} {shift}")